// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.15.0
// source: proto/marketLedger.proto

package marketLedgerGrpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Transaction_TransactionType int32

const (
	Transaction_CASH            Transaction_TransactionType = 0
	Transaction_OWN_INVOICE     Transaction_TransactionType = 1
	Transaction_RESERVED        Transaction_TransactionType = 2
	Transaction_EXPECTED_PAID   Transaction_TransactionType = 3
	Transaction_EXPECTED_PROFIT Transaction_TransactionType = 4
	Transaction_CAPITAL         Transaction_TransactionType = 5
	Transaction_OWES_INVOICE    Transaction_TransactionType = 6
	Transaction_LOSS            Transaction_TransactionType = 7
)

// Enum value maps for Transaction_TransactionType.
var (
	Transaction_TransactionType_name = map[int32]string{
		0: "CASH",
		1: "OWN_INVOICE",
		2: "RESERVED",
		3: "EXPECTED_PAID",
		4: "EXPECTED_PROFIT",
		5: "CAPITAL",
		6: "OWES_INVOICE",
		7: "LOSS",
	}
	Transaction_TransactionType_value = map[string]int32{
		"CASH":            0,
		"OWN_INVOICE":     1,
		"RESERVED":        2,
		"EXPECTED_PAID":   3,
		"EXPECTED_PROFIT": 4,
		"CAPITAL":         5,
		"OWES_INVOICE":    6,
		"LOSS":            7,
	}
)

func (x Transaction_TransactionType) Enum() *Transaction_TransactionType {
	p := new(Transaction_TransactionType)
	*p = x
	return p
}

func (x Transaction_TransactionType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Transaction_TransactionType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_marketLedger_proto_enumTypes[0].Descriptor()
}

func (Transaction_TransactionType) Type() protoreflect.EnumType {
	return &file_proto_marketLedger_proto_enumTypes[0]
}

func (x Transaction_TransactionType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Transaction_TransactionType.Descriptor instead.
func (Transaction_TransactionType) EnumDescriptor() ([]byte, []int) {
	return file_proto_marketLedger_proto_rawDescGZIP(), []int{2, 0}
}

type Transaction_TransactionDCType int32

const (
	Transaction_DEBIT  Transaction_TransactionDCType = 0
	Transaction_CREDIT Transaction_TransactionDCType = 1
)

// Enum value maps for Transaction_TransactionDCType.
var (
	Transaction_TransactionDCType_name = map[int32]string{
		0: "DEBIT",
		1: "CREDIT",
	}
	Transaction_TransactionDCType_value = map[string]int32{
		"DEBIT":  0,
		"CREDIT": 1,
	}
)

func (x Transaction_TransactionDCType) Enum() *Transaction_TransactionDCType {
	p := new(Transaction_TransactionDCType)
	*p = x
	return p
}

func (x Transaction_TransactionDCType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Transaction_TransactionDCType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_marketLedger_proto_enumTypes[1].Descriptor()
}

func (Transaction_TransactionDCType) Type() protoreflect.EnumType {
	return &file_proto_marketLedger_proto_enumTypes[1]
}

func (x Transaction_TransactionDCType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Transaction_TransactionDCType.Descriptor instead.
func (Transaction_TransactionDCType) EnumDescriptor() ([]byte, []int) {
	return file_proto_marketLedger_proto_rawDescGZIP(), []int{2, 1}
}

type Invoice struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          int32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Number      string  `protobuf:"bytes,2,opt,name=number,proto3" json:"number,omitempty"`
	Description string  `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	FaceValue   float32 `protobuf:"fixed32,4,opt,name=face_value,json=faceValue,proto3" json:"face_value,omitempty"`
	IssuerId    int32   `protobuf:"varint,5,opt,name=issuer_id,json=issuerId,proto3" json:"issuer_id,omitempty"`
}

func (x *Invoice) Reset() {
	*x = Invoice{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_marketLedger_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Invoice) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Invoice) ProtoMessage() {}

func (x *Invoice) ProtoReflect() protoreflect.Message {
	mi := &file_proto_marketLedger_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Invoice.ProtoReflect.Descriptor instead.
func (*Invoice) Descriptor() ([]byte, []int) {
	return file_proto_marketLedger_proto_rawDescGZIP(), []int{0}
}

func (x *Invoice) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Invoice) GetNumber() string {
	if x != nil {
		return x.Number
	}
	return ""
}

func (x *Invoice) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Invoice) GetFaceValue() float32 {
	if x != nil {
		return x.FaceValue
	}
	return 0
}

func (x *Invoice) GetIssuerId() int32 {
	if x != nil {
		return x.IssuerId
	}
	return 0
}

type SellOrder struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Invoice     *Invoice `protobuf:"bytes,2,opt,name=invoice,proto3" json:"invoice,omitempty"`
	SellerWants float32  `protobuf:"fixed32,4,opt,name=seller_wants,json=sellerWants,proto3" json:"seller_wants,omitempty"`
}

func (x *SellOrder) Reset() {
	*x = SellOrder{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_marketLedger_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SellOrder) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SellOrder) ProtoMessage() {}

func (x *SellOrder) ProtoReflect() protoreflect.Message {
	mi := &file_proto_marketLedger_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SellOrder.ProtoReflect.Descriptor instead.
func (*SellOrder) Descriptor() ([]byte, []int) {
	return file_proto_marketLedger_proto_rawDescGZIP(), []int{1}
}

func (x *SellOrder) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SellOrder) GetInvoice() *Invoice {
	if x != nil {
		return x.Invoice
	}
	return nil
}

func (x *SellOrder) GetSellerWants() float32 {
	if x != nil {
		return x.SellerWants
	}
	return 0
}

type Transaction struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id                int32                         `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Date              string                        `protobuf:"bytes,2,opt,name=date,proto3" json:"date,omitempty"`
	TransactionType   Transaction_TransactionType   `protobuf:"varint,3,opt,name=transaction_type,json=transactionType,proto3,enum=marketLedgerGrpc.Transaction_TransactionType" json:"transaction_type,omitempty"`
	Details           string                        `protobuf:"bytes,4,opt,name=details,proto3" json:"details,omitempty"`
	TransactionDCType Transaction_TransactionDCType `protobuf:"varint,5,opt,name=transaction_d_c_type,json=transactionDCType,proto3,enum=marketLedgerGrpc.Transaction_TransactionDCType" json:"transaction_d_c_type,omitempty"`
	Value             float32                       `protobuf:"fixed32,6,opt,name=value,proto3" json:"value,omitempty"`
	CustomerId        int32                         `protobuf:"varint,7,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	SellOrderId       int32                         `protobuf:"varint,8,opt,name=sell_order_id,json=sellOrderId,proto3" json:"sell_order_id,omitempty"`
}

func (x *Transaction) Reset() {
	*x = Transaction{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_marketLedger_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Transaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transaction) ProtoMessage() {}

func (x *Transaction) ProtoReflect() protoreflect.Message {
	mi := &file_proto_marketLedger_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transaction.ProtoReflect.Descriptor instead.
func (*Transaction) Descriptor() ([]byte, []int) {
	return file_proto_marketLedger_proto_rawDescGZIP(), []int{2}
}

func (x *Transaction) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Transaction) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *Transaction) GetTransactionType() Transaction_TransactionType {
	if x != nil {
		return x.TransactionType
	}
	return Transaction_CASH
}

func (x *Transaction) GetDetails() string {
	if x != nil {
		return x.Details
	}
	return ""
}

func (x *Transaction) GetTransactionDCType() Transaction_TransactionDCType {
	if x != nil {
		return x.TransactionDCType
	}
	return Transaction_DEBIT
}

func (x *Transaction) GetValue() float32 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *Transaction) GetCustomerId() int32 {
	if x != nil {
		return x.CustomerId
	}
	return 0
}

func (x *Transaction) GetSellOrderId() int32 {
	if x != nil {
		return x.SellOrderId
	}
	return 0
}

type CreateInvoiceReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SellOrder *SellOrder `protobuf:"bytes,2,opt,name=sell_order,json=sellOrder,proto3" json:"sell_order,omitempty"`
}

func (x *CreateInvoiceReq) Reset() {
	*x = CreateInvoiceReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_marketLedger_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateInvoiceReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateInvoiceReq) ProtoMessage() {}

func (x *CreateInvoiceReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_marketLedger_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateInvoiceReq.ProtoReflect.Descriptor instead.
func (*CreateInvoiceReq) Descriptor() ([]byte, []int) {
	return file_proto_marketLedger_proto_rawDescGZIP(), []int{3}
}

func (x *CreateInvoiceReq) GetSellOrder() *SellOrder {
	if x != nil {
		return x.SellOrder
	}
	return nil
}

type CreateInvoiceResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SellOrder   *SellOrder   `protobuf:"bytes,1,opt,name=sell_order,json=sellOrder,proto3" json:"sell_order,omitempty"`
	Transaction *Transaction `protobuf:"bytes,2,opt,name=transaction,proto3" json:"transaction,omitempty"`
	Error       *Error       `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *CreateInvoiceResp) Reset() {
	*x = CreateInvoiceResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_marketLedger_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateInvoiceResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateInvoiceResp) ProtoMessage() {}

func (x *CreateInvoiceResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_marketLedger_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateInvoiceResp.ProtoReflect.Descriptor instead.
func (*CreateInvoiceResp) Descriptor() ([]byte, []int) {
	return file_proto_marketLedger_proto_rawDescGZIP(), []int{4}
}

func (x *CreateInvoiceResp) GetSellOrder() *SellOrder {
	if x != nil {
		return x.SellOrder
	}
	return nil
}

func (x *CreateInvoiceResp) GetTransaction() *Transaction {
	if x != nil {
		return x.Transaction
	}
	return nil
}

func (x *CreateInvoiceResp) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

type Error struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code    string `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *Error) Reset() {
	*x = Error{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_marketLedger_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Error) ProtoMessage() {}

func (x *Error) ProtoReflect() protoreflect.Message {
	mi := &file_proto_marketLedger_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Error.ProtoReflect.Descriptor instead.
func (*Error) Descriptor() ([]byte, []int) {
	return file_proto_marketLedger_proto_rawDescGZIP(), []int{5}
}

func (x *Error) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *Error) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_marketLedger_proto protoreflect.FileDescriptor

var file_proto_marketLedger_proto_rawDesc = []byte{
	0x0a, 0x18, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6d, 0x61, 0x72, 0x6b, 0x65, 0x74, 0x4c, 0x65,
	0x64, 0x67, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x10, 0x6d, 0x61, 0x72, 0x6b,
	0x65, 0x74, 0x4c, 0x65, 0x64, 0x67, 0x65, 0x72, 0x47, 0x72, 0x70, 0x63, 0x22, 0x8f, 0x01, 0x0a,
	0x07, 0x49, 0x6e, 0x76, 0x6f, 0x69, 0x63, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x6e, 0x75, 0x6d, 0x62,
	0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72,
	0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x12, 0x1d, 0x0a, 0x0a, 0x66, 0x61, 0x63, 0x65, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x02, 0x52, 0x09, 0x66, 0x61, 0x63, 0x65, 0x56, 0x61, 0x6c, 0x75,
	0x65, 0x12, 0x1b, 0x0a, 0x09, 0x69, 0x73, 0x73, 0x75, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x69, 0x73, 0x73, 0x75, 0x65, 0x72, 0x49, 0x64, 0x22, 0x73,
	0x0a, 0x09, 0x53, 0x65, 0x6c, 0x6c, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x33, 0x0a, 0x07, 0x69,
	0x6e, 0x76, 0x6f, 0x69, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x6d,
	0x61, 0x72, 0x6b, 0x65, 0x74, 0x4c, 0x65, 0x64, 0x67, 0x65, 0x72, 0x47, 0x72, 0x70, 0x63, 0x2e,
	0x49, 0x6e, 0x76, 0x6f, 0x69, 0x63, 0x65, 0x52, 0x07, 0x69, 0x6e, 0x76, 0x6f, 0x69, 0x63, 0x65,
	0x12, 0x21, 0x0a, 0x0c, 0x73, 0x65, 0x6c, 0x6c, 0x65, 0x72, 0x5f, 0x77, 0x61, 0x6e, 0x74, 0x73,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x02, 0x52, 0x0b, 0x73, 0x65, 0x6c, 0x6c, 0x65, 0x72, 0x57, 0x61,
	0x6e, 0x74, 0x73, 0x22, 0x9c, 0x04, 0x0a, 0x0b, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x64, 0x61, 0x74, 0x65, 0x12, 0x58, 0x0a, 0x10, 0x74, 0x72, 0x61, 0x6e, 0x73,
	0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x2d, 0x2e, 0x6d, 0x61, 0x72, 0x6b, 0x65, 0x74, 0x4c, 0x65, 0x64, 0x67, 0x65, 0x72,
	0x47, 0x72, 0x70, 0x63, 0x2e, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x2e, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65,
	0x52, 0x0f, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70,
	0x65, 0x12, 0x18, 0x0a, 0x07, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x12, 0x60, 0x0a, 0x14, 0x74,
	0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x64, 0x5f, 0x63, 0x5f, 0x74,
	0x79, 0x70, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x2f, 0x2e, 0x6d, 0x61, 0x72, 0x6b,
	0x65, 0x74, 0x4c, 0x65, 0x64, 0x67, 0x65, 0x72, 0x47, 0x72, 0x70, 0x63, 0x2e, 0x54, 0x72, 0x61,
	0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x44, 0x43, 0x54, 0x79, 0x70, 0x65, 0x52, 0x11, 0x74, 0x72, 0x61, 0x6e,
	0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x44, 0x43, 0x54, 0x79, 0x70, 0x65, 0x12, 0x14, 0x0a,
	0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x02, 0x52, 0x05, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x5f,
	0x69, 0x64, 0x18, 0x07, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d,
	0x65, 0x72, 0x49, 0x64, 0x12, 0x22, 0x0a, 0x0d, 0x73, 0x65, 0x6c, 0x6c, 0x5f, 0x6f, 0x72, 0x64,
	0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x08, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x73, 0x65, 0x6c,
	0x6c, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x49, 0x64, 0x22, 0x8b, 0x01, 0x0a, 0x0f, 0x54, 0x72, 0x61,
	0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x12, 0x08, 0x0a, 0x04,
	0x43, 0x41, 0x53, 0x48, 0x10, 0x00, 0x12, 0x0f, 0x0a, 0x0b, 0x4f, 0x57, 0x4e, 0x5f, 0x49, 0x4e,
	0x56, 0x4f, 0x49, 0x43, 0x45, 0x10, 0x01, 0x12, 0x0c, 0x0a, 0x08, 0x52, 0x45, 0x53, 0x45, 0x52,
	0x56, 0x45, 0x44, 0x10, 0x02, 0x12, 0x11, 0x0a, 0x0d, 0x45, 0x58, 0x50, 0x45, 0x43, 0x54, 0x45,
	0x44, 0x5f, 0x50, 0x41, 0x49, 0x44, 0x10, 0x03, 0x12, 0x13, 0x0a, 0x0f, 0x45, 0x58, 0x50, 0x45,
	0x43, 0x54, 0x45, 0x44, 0x5f, 0x50, 0x52, 0x4f, 0x46, 0x49, 0x54, 0x10, 0x04, 0x12, 0x0b, 0x0a,
	0x07, 0x43, 0x41, 0x50, 0x49, 0x54, 0x41, 0x4c, 0x10, 0x05, 0x12, 0x10, 0x0a, 0x0c, 0x4f, 0x57,
	0x45, 0x53, 0x5f, 0x49, 0x4e, 0x56, 0x4f, 0x49, 0x43, 0x45, 0x10, 0x06, 0x12, 0x08, 0x0a, 0x04,
	0x4c, 0x4f, 0x53, 0x53, 0x10, 0x07, 0x22, 0x2a, 0x0a, 0x11, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x44, 0x43, 0x54, 0x79, 0x70, 0x65, 0x12, 0x09, 0x0a, 0x05, 0x44,
	0x45, 0x42, 0x49, 0x54, 0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06, 0x43, 0x52, 0x45, 0x44, 0x49, 0x54,
	0x10, 0x01, 0x22, 0x4e, 0x0a, 0x10, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x49, 0x6e, 0x76, 0x6f,
	0x69, 0x63, 0x65, 0x52, 0x65, 0x71, 0x12, 0x3a, 0x0a, 0x0a, 0x73, 0x65, 0x6c, 0x6c, 0x5f, 0x6f,
	0x72, 0x64, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x6d, 0x61, 0x72,
	0x6b, 0x65, 0x74, 0x4c, 0x65, 0x64, 0x67, 0x65, 0x72, 0x47, 0x72, 0x70, 0x63, 0x2e, 0x53, 0x65,
	0x6c, 0x6c, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x09, 0x73, 0x65, 0x6c, 0x6c, 0x4f, 0x72, 0x64,
	0x65, 0x72, 0x22, 0xbf, 0x01, 0x0a, 0x11, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x49, 0x6e, 0x76,
	0x6f, 0x69, 0x63, 0x65, 0x52, 0x65, 0x73, 0x70, 0x12, 0x3a, 0x0a, 0x0a, 0x73, 0x65, 0x6c, 0x6c,
	0x5f, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x6d,
	0x61, 0x72, 0x6b, 0x65, 0x74, 0x4c, 0x65, 0x64, 0x67, 0x65, 0x72, 0x47, 0x72, 0x70, 0x63, 0x2e,
	0x53, 0x65, 0x6c, 0x6c, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x09, 0x73, 0x65, 0x6c, 0x6c, 0x4f,
	0x72, 0x64, 0x65, 0x72, 0x12, 0x3f, 0x0a, 0x0b, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x6d, 0x61, 0x72, 0x6b,
	0x65, 0x74, 0x4c, 0x65, 0x64, 0x67, 0x65, 0x72, 0x47, 0x72, 0x70, 0x63, 0x2e, 0x54, 0x72, 0x61,
	0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0b, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x61,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x2d, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x6d, 0x61, 0x72, 0x6b, 0x65, 0x74, 0x4c, 0x65, 0x64,
	0x67, 0x65, 0x72, 0x47, 0x72, 0x70, 0x63, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x52, 0x05, 0x65,
	0x72, 0x72, 0x6f, 0x72, 0x22, 0x35, 0x0a, 0x05, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x12, 0x0a,
	0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x63, 0x6f, 0x64,
	0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x32, 0x71, 0x0a, 0x13, 0x4d,
	0x61, 0x72, 0x6b, 0x65, 0x74, 0x4c, 0x65, 0x64, 0x67, 0x65, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x12, 0x5a, 0x0a, 0x0d, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x49, 0x6e, 0x76, 0x6f,
	0x69, 0x63, 0x65, 0x12, 0x22, 0x2e, 0x6d, 0x61, 0x72, 0x6b, 0x65, 0x74, 0x4c, 0x65, 0x64, 0x67,
	0x65, 0x72, 0x47, 0x72, 0x70, 0x63, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x49, 0x6e, 0x76,
	0x6f, 0x69, 0x63, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x23, 0x2e, 0x6d, 0x61, 0x72, 0x6b, 0x65, 0x74,
	0x4c, 0x65, 0x64, 0x67, 0x65, 0x72, 0x47, 0x72, 0x70, 0x63, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x49, 0x6e, 0x76, 0x6f, 0x69, 0x63, 0x65, 0x52, 0x65, 0x73, 0x70, 0x22, 0x00, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_marketLedger_proto_rawDescOnce sync.Once
	file_proto_marketLedger_proto_rawDescData = file_proto_marketLedger_proto_rawDesc
)

func file_proto_marketLedger_proto_rawDescGZIP() []byte {
	file_proto_marketLedger_proto_rawDescOnce.Do(func() {
		file_proto_marketLedger_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_marketLedger_proto_rawDescData)
	})
	return file_proto_marketLedger_proto_rawDescData
}

var file_proto_marketLedger_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_proto_marketLedger_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_marketLedger_proto_goTypes = []interface{}{
	(Transaction_TransactionType)(0),   // 0: marketLedgerGrpc.Transaction.TransactionType
	(Transaction_TransactionDCType)(0), // 1: marketLedgerGrpc.Transaction.TransactionDCType
	(*Invoice)(nil),                    // 2: marketLedgerGrpc.Invoice
	(*SellOrder)(nil),                  // 3: marketLedgerGrpc.SellOrder
	(*Transaction)(nil),                // 4: marketLedgerGrpc.Transaction
	(*CreateInvoiceReq)(nil),           // 5: marketLedgerGrpc.CreateInvoiceReq
	(*CreateInvoiceResp)(nil),          // 6: marketLedgerGrpc.CreateInvoiceResp
	(*Error)(nil),                      // 7: marketLedgerGrpc.Error
}
var file_proto_marketLedger_proto_depIdxs = []int32{
	2, // 0: marketLedgerGrpc.SellOrder.invoice:type_name -> marketLedgerGrpc.Invoice
	0, // 1: marketLedgerGrpc.Transaction.transaction_type:type_name -> marketLedgerGrpc.Transaction.TransactionType
	1, // 2: marketLedgerGrpc.Transaction.transaction_d_c_type:type_name -> marketLedgerGrpc.Transaction.TransactionDCType
	3, // 3: marketLedgerGrpc.CreateInvoiceReq.sell_order:type_name -> marketLedgerGrpc.SellOrder
	3, // 4: marketLedgerGrpc.CreateInvoiceResp.sell_order:type_name -> marketLedgerGrpc.SellOrder
	4, // 5: marketLedgerGrpc.CreateInvoiceResp.transaction:type_name -> marketLedgerGrpc.Transaction
	7, // 6: marketLedgerGrpc.CreateInvoiceResp.error:type_name -> marketLedgerGrpc.Error
	5, // 7: marketLedgerGrpc.MarketLedgerService.CreateInvoice:input_type -> marketLedgerGrpc.CreateInvoiceReq
	6, // 8: marketLedgerGrpc.MarketLedgerService.CreateInvoice:output_type -> marketLedgerGrpc.CreateInvoiceResp
	8, // [8:9] is the sub-list for method output_type
	7, // [7:8] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_proto_marketLedger_proto_init() }
func file_proto_marketLedger_proto_init() {
	if File_proto_marketLedger_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_marketLedger_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Invoice); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_marketLedger_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SellOrder); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_marketLedger_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Transaction); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_marketLedger_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateInvoiceReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_marketLedger_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateInvoiceResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_marketLedger_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Error); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_marketLedger_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_marketLedger_proto_goTypes,
		DependencyIndexes: file_proto_marketLedger_proto_depIdxs,
		EnumInfos:         file_proto_marketLedger_proto_enumTypes,
		MessageInfos:      file_proto_marketLedger_proto_msgTypes,
	}.Build()
	File_proto_marketLedger_proto = out.File
	file_proto_marketLedger_proto_rawDesc = nil
	file_proto_marketLedger_proto_goTypes = nil
	file_proto_marketLedger_proto_depIdxs = nil
}
